# Generated by Django 5.1.6 on 2025-07-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('property_image', models.ImageField(upload_to='rentals/')),
                ('owner_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=20)),
                ('cadastral_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cadastral_document', models.FileField(blank=True, null=True, upload_to='cadastral_docs/')),
                ('card_number', models.CharField(max_length=19)),
                ('expiry_date', models.CharField(max_length=5)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
